### ISSUE TITLE
Erroring with Vue 2.4.x

### ISSUE THREAD

**Issue by eddyerburgh** [jackmellis/require-extension-hooks-vue#16]
It looks like there's a problem with Vue 2.4.0 and require-extension-hooks-vue:

```
TypeError: this._init is not a function
    at Array.Vue$3 (/Users/eyerburgh/Sites/avoriaz-ava-example/node_modules/vue/dist/vue.runtime.common.js:4290:8)
    at transpile (/Users/eyerburgh/Sites/avoriaz-ava-example/node_modules/require-extension-hooks/src/hook.js:26:26)
    at hook (/Users/eyerburgh/Sites/avoriaz-ava-example/node_modules/require-extension-hooks/src/hook.js:15:22)
```

**Comment by eddyerburgh** [comment]
Closed with https://github.com/eddyerburgh/avoriaz-ava-example/issues/10
